### ISSUE TITLE
`NullPointerException` from inside the `MeowBottomNavigation.java`

### ISSUE THREAD

**Issue by simmorsal** [shetmobile/MeowBottomNavigationJava#2]
Hi, this is my implementation of your library:

``` xml
<com.etebarian.meowbottomnavigation.MeowBottomNavigation
    android:id="@+id/bottomNavigation"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:layout_constraintBottom_toBottomOf="parent" />
```

``` java
binding.bottomNavigation.add(new MeowBottomNavigation.Model(0, R.drawable.ic_android_black_24dp));
binding.bottomNavigation.add(new MeowBottomNavigation.Model(1, R.drawable.ic_android_black_24dp));
binding.bottomNavigation.add(new MeowBottomNavigation.Model(2, R.drawable.ic_android_black_24dp));
binding.bottomNavigation.add(new MeowBottomNavigation.Model(3, R.drawable.ic_android_black_24dp));
binding.bottomNavigation.add(new MeowBottomNavigation.Model(4, R.drawable.ic_android_black_24dp));

binding.bottomNavigation.show(2, false);
```

Whenever it comes to `binding.bottomNavigation.show(2, false);` line, or if I comment this, whenever I click on an item, it throws the below error:

``` log
java.lang.NullPointerException: Attempt to invoke interface method 'void com.etebarian.meowbottomnavigation.MeowBottomNavigation$ShowListener.onShowItem(com.etebarian.meowbottomnavigation.MeowBottomNavigation$Model)' on a null object reference
        at com.etebarian.meowbottomnavigation.MeowBottomNavigation.show(MeowBottomNavigation.java:378)
        at com.simmorsal.asdf.ui.activities.main.MainActivity.lambda$setupNav$0$MainActivity(MainActivity.java:76)
        at com.simmorsal.asdf.ui.activities.main.-$$Lambda$MainActivity$9U7KfM_oP3xu2Ln6vC8j8dL8Wa4.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6724)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by oneHamidreza** [comment]
Setup listeners.
